### ISSUE TITLE
Choose communications channel(s)

### ISSUE THREAD

**Issue by brylie** [api-standards/governance#7]
In order for working group members to communicate, we need one or more channels. 

Task
---
* [ ] Discuss communication preferences in this issue
* [ ] Choose communication channels for
  * [ ] Real-time
  * [ ] async
* [ ] Create channel or configure communication solution
* [ ] Invite working group members to communications channel(s)

**Comment by lonelycode** [comment]
Given differing time-zones Async choice will be pretty important.

- Channels:
    - Async: Mailing list, maybe a google groups one (it's what the Golang, Python projects do)?
    - Real Time: IRC (maybe a bit old-school) or Slack? 

Mind you, GH seems to be doing a pretty good job for Async - it's auditable, public, searchable, can tag users for discussions, so maybe not confuse the issue too much and stick with GH and if we need sync, my vote goes for IRC simply because it's been around for donkeys years and is free.

**Comment by brylie** [comment]
Right, I would also like a public discussion thread, so Github seems fine for async.

**Comment by ahmadnassri** [comment]
async: github comments should be perfectly suited, also public.
realtime: gitter?

**Comment by brylie** [comment]
Alright, will you set up a Gitter channel?

**Comment by ahmadnassri** [comment]
done: https://gitter.im/api-standards
